---
# A list of operations in order
operations:
    # Spectrometer initialization
    - init_spec:
        # Give a name to the spectrometer, which will appear in log
        # In this case, a handle is also instantiated and kept in a dictionary
        # for future use.
        name: spec0
        # Address of the spectrometer
        host: 10.1.0.95
        # Spectrometer bitstream for the FPGA
        # If the FPGA is already programmed, remove the line below
        bitstream: spectrometer_16k_quad_2019_Jan_08_1810.fpg
        # The number of channels available in the the above bitstream
        nch: 16384
    # VNA initialization
    - init_vna:
        name: vna0
        channel: 1
        freqstart: 40
        freqstop: 180
        ifbw: 1000
        average: 20
        calib_kit: 23
        power_level: -5
    # Microcontroller initialization
    - init_uc:
        name: uc0
    # My test operation
    - test:
        # Every operation needs a name even if it's a one-time operation
        name: test0
    # switch on power
    - power:
        name: uc0
        5v: 1
        12v: 1
        24v: 1
    # Calibration
    - calib:
        name: vna0
        open: 
            - switch:
                name: uc0
                relay: MTS
                # MTS is a switch, which involves one gpio pin
                # therefore position 1 means on, 0 is off
                position: 1
            - switch:
                name: uc0
                relay: MS2
                position: 4
        short:
            - switch:
                name: uc0
                relay: MTS
                position: 1
            - switch:
                name: uc0
                relay: MS2
                position: 3
        load:
            - switch:
                name: uc0
                relay: MTS
                position: 1
            - switch:
                name: uc0
                relay: MS2
                position: 5
    - save_calib:
        # Check strftime for more format options
        file_name_fmt: _calib_%Y%m%d-%H%M%S
#    - calib_recall:
#        # Check strftime for more format options
#        file_name_fmt: haha.state
    - measure_s:
        name: vna0
        fmt: ri
        # choosing a certain source may involes a few switches
        source:
            - switch:
                name: uc0
                relay: MTS
                position: 1
            - switch:
                name: uc0
                relay: MS2
                position: 6
        file_name_fmt: _l2_%Y%m%d-%H%M%S
    - measure_s:
        name: vna0
        fmt: ri
        source:
            - switch:
                name: uc0
                relay: MTS
                position: 0
            - switch:
                name: uc0
                relay: MS1
                position: 7
            - switch:
                name: uc0
                relay: MS3
                position: 1
        file_name_fmt: _r100_%Y%m%d-%H%M%S
    - measure_s:
        name: vna0
        fmt: ri
        source:
            - switch:
                name: uc0
                relay: MTS
                position: 0
            - switch:
                name: uc0
                relay: MS1
                position: 1
            - switch:
                name: uc0
                relay: MS2
                position: 1
        file_name_fmt: _ant_%Y%m%d-%H%M%S
    # Perform a spectrum measurement
    - measure_spec:
        # Specify the spectrometer
        name: spec0
        # The path where the spectrum txt file is saved
        path: /tmp/reach/
        file_name_fmt: _ant_%Y%m%d-%H%M%S
        source:
            - switch:
                name: uc0
                relay: MTS
                position: 0
            - switch:
                name: uc0
                relay: MS1
                position: 1
        # Hardware integration length.
        # For bitstream above and 250MHz clock, 6103 is for one second
        length: 6103
        # Soft integration length
        # In this case the total integration length is 6103x4, or 4 seconds
        soft: 4
    - measure_spec:
        name: spec0
        path: /tmp/reach/
        file_name_fmt: _c15r5_%Y%m%d-%H%M%S
        source:
            - switch:
                name: uc0
                relay: MTS
                position: 0
            - switch:
                name: uc0
                relay: MS1
                position: 7
            - switch:
                name: uc0
                relay: MS3
                position: 2
    - power:
        name: uc0
        5v: 0
        12v: 0
        24v: 0

# Please refer to logging.config.dictConfig in
# https://docs.python.org/2/library/logging.config.html
logging:
    version: 1
    disable_existing_loggers: false
    
    formatters:
        standard:
            format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    
    handlers:
        console:
            class: logging.StreamHandler
            level: NOTSET
            formatter: standard
    
        file_handler:
            class: logging.handlers.TimedRotatingFileHandler
            level: NOTSET
            formatter: standard
            filename: /tmp/reach_ctrl.log
            when: D

    loggers:
        REACH:
            level: DEBUG
            handlers: [console, file_handler]
            propogate: no
...
