logging:
    version: 1
    disable_existing_loggers: false
    
    formatters:
        standard:
            format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    
    handlers:
        console:
            class: logging.StreamHandler
            level: NOTSET
            formatter: standard
    
        file_handler:
            class: logging.handlers.TimedRotatingFileHandler
            level: NOTSET
            formatter: standard
            filename: /tmp/reach_ctrl.log
            when: D

    loggers:
        REACH:
            level: INFO
            handlers: [console, file_handler]
            propogate: no